workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "pipeline"

variables:
  DUX_VERSION: "0.1.0"

stages:
  - build
  - deploy

build-dux-for-debian:
  stage: build
  image: romzorus/deb-rust-build:v1.0
  script:
   - cargo build --release
   - sed -i "s/PLACEHOLDER_FOR_VERSION/$DUX_VERSION/g" building/deb/dux/DEBIAN/control
   - mkdir -p building/deb/dux/usr/bin
   - mkdir -p building/deb/dux/etc/dux
   - cp target/release/standard building/deb/dux/usr/bin/dux
   - cp building/dux.conf building/deb/dux/etc/dux/dux.conf
   - chmod -R 755 building/deb/dux
   - dpkg-deb --build building/deb/dux
   - mv building/deb/dux.deb building/deb/dux-$DUX_VERSION.deb
  artifacts:
    paths:
    - building/deb/dux-$DUX_VERSION.deb

build-dux-for-fedora:
  stage: build
  image: romzorus/rpm-rust-build:v1.0
  script:
   - cargo build --release
   - sed -i "s/PLACEHOLDER_FOR_VERSION/$DUX_VERSION/g" building/rpm/dux.spec
   - cp building/rpm/dux.spec ~/rpmbuild/SPECS
   - mkdir ~/rpmbuild/BUILDROOT/dux-$DUX_VERSION-0.x86_64/
   - cp target/release/standard ~/rpmbuild/BUILD/dux
   - cp building/dux.conf ~/rpmbuild/BUILD/dux.conf
   - rpmbuild -bb ~/rpmbuild/SPECS/dux.spec
   - cp ~/rpmbuild/RPMS/x86_64/dux-$DUX_VERSION-0.x86_64.rpm dux-$DUX_VERSION.rpm
  artifacts:
    paths:
    - dux-$DUX_VERSION.rpm

upload-to-package-registry:
  stage: deploy
  image: curlimages/curl:8.8.0
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file building/deb/dux-$DUX_VERSION.deb "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/dux/$DUX_VERSION/dux-$DUX_VERSION.deb"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dux-$DUX_VERSION.rpm "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/dux/$DUX_VERSION/dux-$DUX_VERSION.rpm"'
  rules:
   - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "pipeline"
